name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: execute
      run: ./sobel
