name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SDL install
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev 
    - name: make
      run: ./CMakeGCC.sh
    - name: execute
      run: ./bin/make/sobel
